---

- name: Test if distribution is RedHat
  assert:
    that: ansible_os_family == "RedHat"

- name: Install Redis
  package:
    name: "{{ redis_pkg }}"
  notify:
    - Restart Redis
  tags:
    - redis_pkg

- name: Configure Redis
  template:
    src: redis.conf.j2
    dest: "{{ redis_config_location }}"
  notify:
    - Restart Redis
  tags:
    - redis_config

- name: Configure Redis sysconfig file
  template:
    src: redis_sysconfig.j2
    dest: /etc/sysconfig/redis
  notify:
    - Restart Redis
  tags:
    - redis_config

- name: Enable and start Redis
  service:
    name: redis
    state: started
    enabled: true
  tags:
    - redis_service
