---

- name: Install redis
  yum: 
    name=redis
    state=present
  when: 
    ansible_os_family == "RedHat"

- name: Enable and start redis
  service:
    name=redis
    state=started
    enabled=true
